DROP TABLE IF EXISTS users_movies CASCADE;

CREATE TABLE users_movies (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  movie_id INTEGER REFERENCES movies(id) ON DELETE CASCADE
);
